name: ekw-promotion

channels:
  - defaults
  - conda-forge
  - OpenSourceEconomics

dependencies:
  - pypdf2 
  - pip
  - click
  - codecov
  - statsmodels
  - pygraphviz>=1.5
  - doc8
  - deepdiff
  - estimagic>=0.0.9
  - jupyterlab
  - matplotlib>=3.0.0
  - numpydoc
  - pyaml
  - pytest-cov
  - pytest-xdist    
  - numpy
  - restructuredtext_lint
  - scipy>=1.2.1
  - black>=20.8b1
  - flake8
  - pytest-flake8
  - pytest
  - tox-conda
  - respy
  - pip:
      - pre-commit
      - pysftp
      - pytest-black
      - PyPDF2
      - pandas>=1.0.5
