name: ekw-promotion

channels:
  - defaults
  - conda-forge
  - OpenSourceEconomics

dependencies:
  - python=3.7.3
  - pypdf2 
  - pip=19.0.3
  - chaospy
  - click
  - codecov
  - statsmodels
  - pygraphviz>=1.5
  - doc8
  - deepdiff
  - estimagic>=0.0.9
  - jupyterlab
  - matplotlib>=3.0.0
  - mkl
  - nbsphinx=0.4.2
  - numba>=0.43.1
  - numpydoc
  - pandas<1.00
  - pyaml
  - pytest-cov
  - pytest-xdist    
  - seaborn
  - numpy
  - pyarrow
  - restructuredtext_lint
  - scipy>=1.2.1
  - Sphinx>=2.0.0
  - black>=20.8b1
  - flake8
  - pytest-flake8
  - pytest
  - sphinx-autobuild
  - tox-conda
  - pip:
      - git+https://github.com/OpenSourceEconomics/respy
      - apprise
      - pre-commit
      - pysftp
      - pytest-black
      - Py-BOBYQA
      - DFO-LS
      - PyPDF2
      - jupyterlab
      - pygmo
