name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
           activate-environment: ekw-promotion
           environment-file: configurations/environment.yml
           python-version: 3.6
           auto-activate-base: false
    - name: compile appendix
      uses: dante-ev/latex-action@master
      with:
        root_file: appendix/main.tex
    - name: compile latex
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        git submodule init
        git submodule update
        run-content -g
        pytest
