name: Continuous Integration

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1.0.2
      with:
           activate-environment: ekw-promotion
           environment-file: configurations/environment.yml
           python-version: 3.6
           auto-activate-base: false
    - name: install latex dependencies
      run: |
        sudo apt-get update
        sudo apt-get install texlive texlive-science texlive-latex-extra texlive-bibtex-extra texlive-fonts-extra texlive-lang-german
        sudo snap install pdftk
        sudo texhash
    - name: compile latex
      shell: bash -l {0}
      run: |
        export PATH="$PATH:/usr/share/miniconda/bin"
        source .envrc
        git submodule init
        git submodule update
        run-content -f
        pytest
